##--------------------------------------------------------------------
## rmqtt-message-storage
##--------------------------------------------------------------------

##ram, redis
storage.type = "ram"

#ram
storage.ram.cache_capacity = "3G"

#redis
storage.redis.url = "redis://127.0.0.1:6379/"
storage.redis.prefix = "message-{node}"

##cleanup
cleanup_count = 5000
