##--------------------------------------------------------------------
## rmqtt-message-storage
##--------------------------------------------------------------------

##ram, sled, redis
#ram and sled not supported yet.
storage.type = "redis"

#redis
storage.redis.url = "redis://127.0.0.1:6379/"
storage.redis.prefix = "message-{node}"

##cleanup
cleanup_count = 5000
