##--------------------------------------------------------------------
## rmqtt-session-storage
##--------------------------------------------------------------------

storage_type = "sled"
#sled
sled.path = "/var/log/rmqtt/.cache/session"
sled.cache_capacity = "1G"

##@see https://lib.rs/crates/tokio-cron-scheduler
cleanup_cron = "0 0 3 * * * *"