##--------------------------------------------------------------------
## rmqtt-storage
##--------------------------------------------------------------------

storage_type = "sled"
sled.path = "/var/log/rmqtt/.cache"
sled.cache_capacity = "1G"