##--------------------------------------------------------------------
## rmqtt-message-storage
##--------------------------------------------------------------------

##sled, redis
storage.type = "redis"

#sled
storage.sled.path = "/var/log/rmqtt/.cache/message/{node}"
storage.sled.cache_capacity = "3G"

#redis
storage.redis.url = "redis://127.0.0.1:6379/"
storage.redis.prefix = "message-{node}"

##cleanup
cleanup_count = 5000
