[package]
name = "rmqtt-storage"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true


[dependencies]
rmqtt.workspace = true
serde = { workspace = true, features = ["derive"] }
sled = "0.34"