[package]
name = "simple_tls"
version = "0.1.0"
edition.workspace = true

[dependencies]
rmqtt = { workspace = true, features = ["tls"] }
tokio = { workspace = true, features = ["macros"] }
simple_logger.workspace = true
log.workspace = true

