[package]
name = "rmqtt-http-api"
version = "0.1.0"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2021"

[dependencies]
rmqtt.workspace = true
serde = { workspace = true, features = ["derive"] }
salvo = { version = "0.63", features = ["affix"] }
