[package]
name = "rmqtt-message-storage"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true


[dependencies]
rmqtt.workspace = true
rmqtt-storage = "0.2"
#rmqtt-storage = { path = "../../../rmqtt-storage"}
serde = { workspace = true, features = ["derive"] }